steps:
  # Build and Push using Kaniko
  - name: "gcr.io/kaniko-project/executor:latest"
    args:
      [
        "--destination=gcr.io/$PROJECT_ID/$_REPO_NAME",
        "--cache=true",
        "--cache-ttl=24h",
      ]

  # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "$_REPO_NAME",
        "--image",
        "gcr.io/$PROJECT_ID/$_REPO_NAME",
        "--region",
        "europe-west1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--memory",
        "512Mi",
      ]
